name: lokerin
description: "Aplikasi Pencari Lowongan Kerja Yogyakarta â€“ Proyek PAM."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_local_notifications: ^19.5.0
  intl: ^0.20.2
  google_fonts: ^6.3.2
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  bcrypt: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/